export const ADD_CARD_TO_DECK = "ADD_CARD_TO_DECK";
export const MARK_CARD_CORRECT = "MARK_CARD_CORRECT";
export const MARK_CARD_INCORRECT = "MARK_CARD_INCORRECT";
export const ADD_NEW_DECK = "ADD_NEW_DECK";
